export enum Responses {

  USER_ALREADY_EXISTS = 'user exists',
  USER_SUBSCRIBED = "USER_SUBSCRIBED",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_UPDATED = "USER_UPDATED",
  USER_DELETED = "USER_DELETED",
  USER_INCORRECT_PASSWORD = "USER_INCORRECT_PASSWORD",
  USER_LOGIN = "USER_LOGIN",
  ACCESS_DENIED = "ACCESS_DENIED"
}