export enum Responses {

    USER_ALREADY_EXISTS = 'user exists',
    USER_SUBSCRIBED = "USER_SUBSCRIBED",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    USER_UPDATED = "USER_UPDATED",
    USER_DELETED = "USER_DELETED",
    USER_INCORRECT_PASSWORD = "USER_INCORRECT_PASSWORD",
    USER_LOGIN = "USER_LOGIN",
    ACCESS_DENIED = "ACCESS_DENIED",
    USER_NAME_IS_REQUIRED = "USER_NAME_IS_REQUIRED",
    USER_MAIL_IS_REQUIRED = "USER_MAIL_IS_REQUIRED",
    USER_PASSWORD_IS_REQUIRED = "USER_PASSWORD_IS_REQUIRED",
    USER_ALREADY_VALIDATED = "USER_ALREADY_VALIDATED",
    INVALID_CODE_MAIL = "INVALID_CODE_MAIL",
    USER_MAIL_VALIDATE = "USER_MAIL_VALIDATE",
    USER_MAIL_NOT_VALIDATED = "USER_MAIL_NOT_VALIDATED",
    EVENT_ALREADY_EXISTS = "EVENT_ALREADY_EXISTS",
    EVENT_CREATED = "EVENT_CREATED"
}